// POST /api/export — export a conversation's audit report.
// Body: { conversationId, format: "markdown" | "json" }

import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";

export const runtime = "nodejs";

const SEV_RANK: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  const conversationId = String(body.conversationId || "");
  const format = body.format === "json" ? "json" : "markdown";
  if (!conversationId) return NextResponse.json({ error: "conversationId required" }, { status: 400 });

  const conv = await db.conversation.findUnique({
    where: { id: conversationId },
    include: {
      messages: { orderBy: { createdAt: "asc" } },
      findings: { orderBy: [{ severity: "asc" }, { createdAt: "asc" }] },
      exploits: { orderBy: [{ severity: "asc" }, { createdAt: "asc" }] },
    },
  });
  if (!conv) return NextResponse.json({ error: "not found" }, { status: 404 });

  if (format === "json") {
    return NextResponse.json({
      title: conv.title,
      createdAt: conv.createdAt,
      updatedAt: conv.updatedAt,
      messages: conv.messages.map((m) => ({ role: m.role, content: m.content, createdAt: m.createdAt })),
      findings: conv.findings,
      exploits: conv.exploits,
    });
  }

  // Markdown report
  const sortedExploits = [...conv.exploits].sort((a, b) => (SEV_RANK[a.severity] - SEV_RANK[b.severity]) || a.title.localeCompare(b.title));
  const topSev = sortedExploits[0]?.severity || "info";
  const lines: string[] = [];
  lines.push(`# Security Audit — ${conv.title}`, "");
  lines.push(`> Generated by Vexor on ${new Date().toISOString()}`, "");
  lines.push(`---`, "");
  lines.push(`**Risk Level:** ${topSev.toUpperCase()}`, "");
  lines.push(`**Findings vault:** ${conv.findings.length} sensitive artifact(s)`, "");
  lines.push(`**Exploits catalogued:** ${sortedExploits.length}`, "");
  lines.push(`---`, "");

  if (sortedExploits.length) {
    lines.push("", "## Exploit & Patch Catalog", "");
    // Remediation summary
    const open = sortedExploits.filter((e) => (e.status || "open") === "open").length;
    const remediated = sortedExploits.filter((e) => e.status === "remediated").length;
    const verified = sortedExploits.filter((e) => e.status === "verified").length;
    lines.push(`**Remediation:** ${open} open · ${remediated} remediated · ${verified} verified`, "");
    lines.push("---", "");
    sortedExploits.forEach((e, i) => {
      const status = e.status || "open";
      const statusBadge = status === "open" ? "🔴 OPEN" : status === "remediated" ? "🟡 REMEDIATED" : "🟢 VERIFIED";
      lines.push(`### Exploit ${i + 1} — ${e.title} (Severity: ${e.severity}) [${statusBadge}]`, "");
      if (e.location) lines.push(`**Location:** ${e.location}`, "");
      if (e.exploitInstructions) lines.push(`**Instructions:** ${e.exploitInstructions}`, "");
      lines.push(``, `**Exploit code:**`, "```" + (e.language || "bash"), e.exploitCode || "(none)", "```", "");
      if (e.patchInstructions) lines.push(`**Patch instructions:** ${e.patchInstructions}`, "");
      lines.push(``, `**Patch code:**`, "```" + (e.language || "lang"), e.patchCode || "(none)", "```", "");
      lines.push(`-----`, "");
    });
  }

  if (conv.findings.length) {
    lines.push("", "## Findings Vault", "");
    const byCat: Record<string, typeof conv.findings> = {};
    for (const f of conv.findings) (byCat[f.category] ||= []).push(f);
    for (const [cat, items] of Object.entries(byCat)) {
      lines.push(`### ${cat} (${items.length})`, "");
      for (const f of items) lines.push(`- [${f.severity}] ${f.type}: \`${f.masked}\`  — \`${f.location}\` (${f.sourceTool})`);
      lines.push("");
    }
  }

  lines.push("", "## Full Conversation Transcript", "");
  for (const m of conv.messages) {
    lines.push(`**${m.role}:**`, "", m.content, "");
  }

  const md = lines.join("\n");
  return new Response(md, {
    headers: {
      "content-type": "text/markdown; charset=utf-8",
      "content-disposition": `attachment; filename="vexor-audit-${conv.id}.md"`,
    },
  });
}
